version: 2.1
orbs:
  coveralls: coveralls/coveralls@1.0.4
commands:
  build:
    description: 'Build command that accepts Angular project name as parameter'
    parameters:
      project:
        type: string
        default: ''
    docker:
      - image: circleci/node:lts-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm ci

      # force update the webdriver, so it runs with latest version of Chrome
      - run: cd ./node_modules/protractor && npm i webdriver-manager@latest

      # because we use "npm ci" to install NPM dependencies
      # we cache "~/.npm" folder
      - save_cache:
          paths:
            - ~/.npm
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: npm run style
      - run: npm run lint

      - run: npm run build:prod --project << parameters.project >>
      - run: npm test -- --watch=false --project << parameters.project >>
      - run: npm run test:coverage -- --watch=false --project << parameters.project >>
      - run: npm run e2e --project << parameters.project >>

      - store_test_results:
          path: ./test_results
      - store_artifacts:
          path: ./coverage

      # upload coverage report to coveralls for readme badge support
      # requires config.yml version 2.1 and orbs: coveralls: coveralls/coveralls@1.0.4
      # requires coveralls account and token named COVERALLS_REPO_TOKEN specific to repo to be stored in CircleCI
      - coveralls/upload

      - run:
          name: Tar & Gzip compiled app
          command: tar zcf dist.tar.gz dist/<< parameters.project >>
      - store_artifacts:
          path: dist.tar.gz

      - run:
          name: Move compiled app to workspace
          command: |
            set -exu
            mkdir -p /tmp/workspace/dist
            mv dist/<< parameters.project >> /tmp/workspace/dist/
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - dist/<< parameters.project >>
jobs:
  master:
    steps:
      - build:
          project: 'local-eather-app'
  deploy:
    docker:
      - image: circleci/node:lts
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run: npx now --token $NOW_TOKEN --platform-version 2 --prod --name localcast-weather /tmp/workspace/dist/local-weather-app --confirm
  verifyProjects:
    # this job is only here to verify sample code from the book, remove it in your own projects
    docker:
      - image: circleci/node:lts-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm ci

      # force update the webdriver, so it runs with latest version of Chrome
      - run: cd ./node_modules/protractor && npm i webdriver-manager@latest

      # because we use "npm ci" to install NPM dependencies
      # we cache "~/.npm" folder
      - save_cache:
          paths:
            - ~/.npm
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Verify sample codes for the book chapters
          command: node ./bin/verifyProjects.js

workflows:
  version: 2
  build-test-and-approval-deploy:
    jobs:
      # - verifyProjects # this job is only here to verify sample code from the book, remove it in your own projects
      - master
      - hold:
          type: approval
          requires:
            - master
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - hold
