# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Verify Projects per Book Chapter

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js lts
      uses: actions/setup-node@v1
      with:
        node-version: lts
    - run: npm ci
    - run: node bin/verifyProjects.js
      env:
        CI: true
