# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Verify Projects per Book Chapter

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: npm ci         
  ch2:
    needs: setup
    runs-on: ubuntu-latest
    steps:  
    - run: npx ng build --prod --project ch2
    - run: npx ng test --watch=false --project ch2
    - run: npx ng test --code-coverage --watch=false --project ch2
    - run: npm run e2e ch2
  ch3:
    needs: setup
    runs-on: ubuntu-latest
    steps:      
    - run: npx ng build --prod --project ch3
    - run: npx ng test --watch=false --project ch3
    - run: npx ng test --code-coverage --watch=false --project ch3
    - run: npm run e2e ch3
